require 'mongoid'
require 'audit'
require 'audit_problem/base'
require 'audit_problem/missing_issue'

require 'audit_problem/entry_specific'
require 'audit_problem/invalid_document_number'
require 'audit_problem/missing_bulkdata_file'
require 'audit_problem/missing_title'
require 'audit_problem/missing_topic'
require 'audit_problem/missing_agency'
require 'audit_problem/missing_agency_name'
require 'audit_problem/missing_granule_class'
require 'audit_problem/missing_page_range'

require 'audit_problem/bulkdata_element_too_large'
require 'audit_problem/agency_element_too_large'
